### ISSUE TITLE
Improve indentation, code style and pipeline/workflow usage consistency

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/training#209]
- [x] Some code blocks are indented with 4 spaces. Others with 2.
  - [x] Make new lines between blocks in processes consistent
  - [x] Sometimes there are spaces around parenthesis. Some other times there isn't any space or a mix of it
  - [x] Sometimes `option:value`, some other times `option: value` (`header: true`, `flat:true`)
  - [ ] Sometimes operators are separated by a line. Some other times, they aren't. 
  - [x] The words _workflow_ and _pipeline_ are used interchangeably, but if we mean the same thing we should stick one. If we don't (like in the Tower documentation), then we should stick to the proper name in every situation.
  - [x] Image name and image name tag are both called tags which can be confusing.
  - [ ] NCBI instructions when translated should have the words in English the way they are in the NCBI portal. They're currently partially translated into the Portuguese translation
  - [x] method/channel factories are used interchangeably but they should be introduced as methods and then only called factories.
  - [x] Sometimes, a process is called a task, and a task is called a process. A task is a process instance and should be always clear to the reader.
  - [x] Sometimes code within the string block is indented, and sometimes it's not.
  - [x] Avoid implicit syntax such as not mentioning `script:` before `"""`
  - [x] Use `debug true` instead of `echo true`
  - [x] process names should be uppercase
  - [x] Keep the basic training consistent in terms of Nextflow version (remove `export NXF_VER=20.10.0` in Tower section)
  - [x] Add space around values separated by `,` ([1, 2] instead of [1,2]) or regular operators (`4 % 2` or `4 + 2` instead of `4%2` or `4+2`). Exceptions here are bash that requires no spaces such as in `export name=example` or globbing in `{1,2}`.

**Comment by mribeirodantas** [comment]
I would like to discuss a bit a few of the points I raised above and would love to hear your feedback, @ewels and @christopher-hakkaart.

# Workflow vs Pipeline
I'm not completely happy with the definition I see [on the Tower documentation](https://help.tower.nf/22.4/core-concepts/definitions/), but one definition is better than none, so I'm fine to propagate it over here 😅 (TLDR: The script is a workflow. The workflow + compute environment + data + launch parameters is the pipeline). What do you think about this? Should I stick to this definition and update the training material to use the correct word at the correct places?

# Task vs process vs job
I think we're all fine with the concept that nextflow tasks are nextflow process instances. I think we should avoid using other words for that, such as job. And having said that, the idea is to make sure the right word is used at the right places in the training material.

# Docker images name and tags
I think that because we can tag an image with a name, and also tag an image name with a tag ([it's the word Docker uses in the official documentation](https://docs.docker.com/engine/reference/commandline/tag/)), we feel like calling everything a tag, but we shouldn't. The idea is to use the right word at the right case in the training material.

# Implicit keyword such as `script` before `"""`
At first I felt we should never do that, but at the same time it could be useful to do it once at the right place (process section) to show it's possible, but then avoid it as IMHO explicit is better than implicit (blame my pythonic background for that 😆 ).

# FOO BAR
It's not always that we have given good names to our variables and functions. Even though I think it's also important to use foo/bar here and there, to make it clear that the person can name it like they want, maybe it's named like this too many times in the training material. What do you think?

# Method/function/factory/operator
I believe it's useful to call them functions (or even methods) in the Groovy section, or somewhere at the beginning, but once it's evident we're talking about [special] variables and [special] functions, I think we should stick to the more precise nomenclature: Channel factories and channel operators. What do you think?

**Comment by ewels** [comment]
> Workflow vs pipeline

I think the definition makes sense for Tower, but for pure Nextflow I'm not sure that "pipeline" would be used enough to make this distinction clear. I think either leave things as they are, or just choose one to use (workflow I guess).

> Task vs process vs job

For me I usually think of job as being the bit that's actually submitted to the scheduler. So all 3 are different. But again job is pretty rare with that definition and so happy to essentially drop it.

> Docker images name and tags

For me this one is quite clear?

* Image: `nextflow-io/nextflow`
* Tag: `:latest`

> Script

Yes I always use `script:`. I think it's confusing to omit it. At most I think it should be a `note` admonition, but not ever used in examples.

> Foo bar

Difficult to generalise. I doubt foo and bar are an issue, but confusing examples may be. Case by case situation.

> Channel factories and channel operators

Yes, agree.

**Comment by mribeirodantas** [comment]
Very good points, @ewels. Agreed.
